### ISSUE TITLE
User is not prompted to stop at 256 characters in description field

### ISSUE THREAD

**Issue by meravhoffman** [gmcgath/songid#12]
I have twice submitted two very long titles to the MP3 description field in the "Add a New Clip" area, and was not prompted to stop or stopped by the character limit in the "Description" field. Neither clip was successfully submitted.

**Comment by gmcgath** [comment]
I've added a "maxlength=256" attribute to the field. That works with Firefox and Safari in my testing. It should be tested with other browsers.
