### ISSUE TITLE
Submitting a clip triggered "Internal Error" issue

### ISSUE THREAD

**Issue by meravhoffman** [gmcgath/songid#13]
When I attempted to submit a report on the clip Three Fine Daughters of Farmer Brown, I entered the data as follows.

What can you hear? 

x Performance

Performance

x Song

x Group Performance

x Female Performers

I can identify this song
 
x The Three Fine Daughters of Farmer Brown

I can identify the performers

x Seanan McGuire
x Batya Wittenberg
x Merav Hoffman

One or more instruments are present:

x Percussion

x Drums (frame or bodhran)

And then I hit submit and got a red Internal Error message at the top of my screen.

**Comment by gmcgath** [comment]
This was a complicated one to fix; there were multiple bugs, and along the way I came upon some unimplemented aspects that I just had to finish. A couple of minutes ago I submitted a report on "Farmer Brown" giving the data listed above, and it's now working. The report lists the title, performers, and instruments.

**Comment by meravhoffman** [comment]
Awesome. I will test it when I get home from the Pride Parade, as I'm unsure things will work on mobile.

**Comment by meravhoffman** [comment]
This seems to be working now! I think this can be closed. I'll open a fresh issue if it crops up again.
