### ISSUE TITLE
No confirmation on account creation screen

### ISSUE THREAD

**Issue by meravhoffman** [gmcgath/songid#2]
As I user, when I create a personal account, no confirmation or rejection message is returned.

Requirements:
I want the system to send a reply to my attempt to create an account that says either "Your account has been created. Your username is X." or "Your account cannot be created, please make sure that your username and password are in the correct format, per the instructions on the account creation page."

**Comment by gmcgath** [comment]
What I'm seeing is that it's coming back with an error code of -1, which indicates an unexpected error in the code. This may be related to my converting the code to Idiorm. To complicate things. I can't log into the server with SSH or SFTP right now. I can test it on my local machine but will have trouble fixing the problem on the main server till that's resolved.

**Comment by gmcgath** [comment]
This should be fixed now. There were problems with both the code and the database.

**Comment by meravhoffman** [comment]
This appears to be resolved.
