### ISSUE TITLE
Available Sound Clips page displaying PHP version data

### ISSUE THREAD

**Issue by meravhoffman** [gmcgath/songid#5]
The PHP version and data is displaying on the Available Sound Clips page.
![php data displaying on main page](https://cloud.githubusercontent.com/assets/13068614/8394048/ce43a23e-1cf5-11e5-82a1-2fba63364c01.png)

**Comment by meravhoffman** [comment]
There are about 8 screens worth of PHP data. I submit that users will find this confusing. :)

**Comment by gmcgath** [comment]
That's a debugging feature. I'd like to keep it for a while, but I can add a show/hide control to make it less annoying.

**Comment by meravhoffman** [comment]
That's fair.
