### ISSUE TITLE
Show Clips Without Reports shows nothing

### ISSUE THREAD

**Issue by meravhoffman** [gmcgath/songid#6]
When I click the Show Clips WIthout Reports button all clips are hidden.

**Comment by gmcgath** [comment]
It may be that all clips have reports. 

However, I tried to upload another clip and it told me only MP3 files are allowed even though I gave it an MP3. I'll have to look at that.

**Comment by gmcgath** [comment]
I fixed the MP3 upload bug, then uploaded a clip called "Short MP3 by Tom Smith." It shows in clips without reports.
